// import 'prismjs/themes/prism.css'
// import 'prismjs/themes/prism-dark.css'
// import 'prismjs/themes/prism-coy.css'
// import 'prismjs/themes/prism-funky.css'
import 'prismjs/themes/prism-okaidia.css'
import './src/font.css'
